name: Trackmate
description: TrackMate - Fitness Tracking Platform
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.2.2

  # State management
  flutter_bloc: ^9.1.1
  equatable: ^2.0.5

  # Networking
  dio: ^5.4.3+1
  dio_cookie_manager: ^3.4.0
  cookie_jar: ^4.0.9

  # Navigation
  go_router: ^17.1.0

  # DI
  get_it: ^9.2.1

  # Functional programming
  dartz: ^0.10.1

  # Charts
  fl_chart: ^1.2.0

  # WebSocket
  web_socket_channel: ^3.0.1

  # Local storage (settings only)
  shared_preferences: ^2.5.4
  pedometer: ^4.0.0
  permission_handler: ^11.3.1
  # Utils
  logger: ^2.3.0
  intl: ^0.19.0
  path_provider: ^2.1.5
#  flutter_background_service: ^2.0.0
#  flutter_background_service_android: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^10.0.0
  mocktail: ^1.0.4
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  
  assets:
    - assets/images/