"""Add non-negative constraints to trainer application

Revision ID: 9c22503b2916
Revises: 93d7f563d51b
Create Date: 2026-04-14 06:36:42.854640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c22503b2916'
down_revision: Union[str, None] = '93d7f563d51b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
