"""add_whatsapp_features_to_messages

Revision ID: acd24685658b
Revises: 05f64f627398
Create Date: 2026-03-25 13:46:03.946492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'acd24685658b'
down_revision: Union[str, None] = '05f64f627398'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('is_pinned', sa.Boolean(), nullable=False))
    op.add_column('messages', sa.Column('reply_to_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'messages', 'messages', ['reply_to_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_column('messages', 'reply_to_id')
    op.drop_column('messages', 'is_pinned')
    # ### end Alembic commands ###
